name: GitHub Actions Demo

on: 
  push:
    branches:    
      - main
    paths-ignore: 
      - '.github'
      
  workflow_dispatch:
    
  pull_request:
    branches: 
      - main

  schedule:
    - cron: '15 16 * * SAT'

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - run: echo "Hello, World!"
